* Incremental Indexing
** ChunkedList
*** 0a03742
running 4 tests
test inc_index_100kb ... bench:   4,214,167 ns/iter (+/- 195,186)
test inc_index_1mb   ... bench:  49,089,420 ns/iter (+/- 3,037,795)
test index_100kb     ... bench:   2,832,898 ns/iter (+/- 112,752)
test index_1mb       ... bench:  32,433,268 ns/iter (+/- 3,126,444)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured
** Vec
*** 44255df
running 6 tests
test inc_index_100kb ... bench:   4,490,793 ns/iter (+/- 96,394)
test inc_index_100mb ... bench: 2,076,416,674 ns/iter (+/- 121,622,878)
test inc_index_10mb  ... bench: 461,516,680 ns/iter (+/- 1,057,615)
test inc_index_1mb   ... bench:  42,484,862 ns/iter (+/- 343,886)
test index_100kb     ... bench:   2,861,060 ns/iter (+/- 21,141)
test index_1mb       ... bench:  37,072,071 ns/iter (+/- 98,597)

test result: ok. 0 passed; 0 failed; 0 ignored; 6 measured

* Indexing Benchmark
** ChunkedList
*** 1e8278e 
running 3 tests
test index_100kb ... bench:   3,887,964 ns/iter (+/- 150,349)
test index_10mb  ... bench: 544,717,565 ns/iter (+/- 35,294,511)
test index_1mb   ... bench:  44,500,864 ns/iter (+/- 5,414,371)
** Simplified Indexing
*** bb796ee ~25mb/s 1 Thread
running 4 tests
test index_100kb ... bench:   2,845,210 ns/iter (+/- 17,947)
test index_100mb ... bench: 3,923,865,654 ns/iter (+/- 313,731,489)
test index_10mb  ... bench: 474,433,864 ns/iter (+/- 31,567,143)
test index_1mb   ... bench:  37,581,279 ns/iter (+/- 2,284,396)
*** 7d3457e ~20mb/s 1 Thread
running 3 tests
test index_100kb ... bench:   4,605,657 ns/iter (+/- 61,807)
test index_10mb  ... bench: 483,464,894 ns/iter (+/- 44,082,738)
test index_1mb   ... bench:  40,494,120 ns/iter (+/- 233,552)
** Old version
*** 77b5891
running 4 tests
test index_100kb ... bench:   3,767,254 ns/iter (+/- 178,005)
test index_100mb ... bench: 7,770,690,219 ns/iter (+/- 652,561,624)
test index_10mb  ... bench: 665,334,106 ns/iter (+/- 103,991,620)
test index_1mb   ... bench:  42,403,164 ns/iter (+/- 2,008,641)
** "fast" version
*** 3abe7ad
running 3 tests
test index_100kb ... bench:   4,731,685 ns/iter (+/- 1,381,734)
test index_10mb  ... bench: 361,460,113 ns/iter (+/- 17,927,911)
test index_1mb   ... bench:  45,964,568 ns/iter (+/- 3,745,579)

test result: ok. 0 passed; 0 failed; 0 ignored; 3 measured
*** ed45cc0
running 4 tests
test index_100kb ... bench:   3,406,413 ns/iter (+/- 625,404)
test index_100mb ... bench: 3,092,109,862 ns/iter (+/- 235,616,795)
test index_10mb  ... bench: 302,353,024 ns/iter (+/- 15,041,106)
test index_1mb   ... bench:  29,847,550 ns/iter (+/- 3,133,100)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured
** ChunkedStorage
*** d69ddac
running 4 tests
test index_100kb ... bench:   4,977,220 ns/iter (+/- 607,944)
test index_100mb ... bench: 1,333,506,148 ns/iter (+/- 69,124,141)
test index_10mb  ... bench: 140,526,823 ns/iter (+/- 5,097,964)
test index_1mb   ... bench:  25,265,408 ns/iter (+/- 3,438,457)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured
*** c6f492e
running 4 tests
test index_100kb ... bench:   5,944,031 ns/iter (+/- 928,082)
test index_100mb ... bench: 1,550,940,637 ns/iter (+/- 171,962,938)
test index_10mb  ... bench: 155,303,666 ns/iter (+/- 7,628,189)
test index_1mb   ... bench:  26,913,485 ns/iter (+/- 3,122,927)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured

*** 3bb2c31
running 4 tests
test index_100kb ... bench:   4,897,557 ns/iter (+/- 1,234,864)
test index_100mb ... bench: 1,958,370,581 ns/iter (+/- 80,890,964)
test index_10mb  ... bench: 198,153,642 ns/iter (+/- 5,004,508)
test index_1mb   ... bench:  31,528,967 ns/iter (+/- 2,185,275)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured


* Boolean_Query
** Chunked List
*** abc6406
**** LIST_CHUNKSIZE: 8
running 12 tests
test atom_frequent::large_collection           ... bench:     146,049 ns/iter (+/- 428)
test atom_frequent::large_collection_first_ten ... bench:         214 ns/iter (+/- 14)
test atom_frequent::large_docs                 ... bench:      13,610 ns/iter (+/- 984)
test atom_frequent::large_docs_first_ten       ... bench:         204 ns/iter (+/- 1)
test atom_frequent::typical                    ... bench:      13,513 ns/iter (+/- 39)
test atom_frequent::typical_first_ten          ... bench:         202 ns/iter (+/- 1)
test atom_seldom::large_collection             ... bench:       1,444 ns/iter (+/- 66)
test atom_seldom::large_collection_first_ten   ... bench:         237 ns/iter (+/- 12)
test atom_seldom::large_docs                   ... bench:       1,248 ns/iter (+/- 3)
test atom_seldom::large_docs_first_ten         ... bench:         227 ns/iter (+/- 7)
test atom_seldom::typical                      ... bench:         292 ns/iter (+/- 13)
test atom_seldom::typical_first_ten            ... bench:         254 ns/iter (+/- 2)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured
**** LIST_CHUNKSIZE: 16
running 12 tests
test atom_frequent::large_collection           ... bench:     139,485 ns/iter (+/- 2,920)
test atom_frequent::large_collection_first_ten ... bench:         205 ns/iter (+/- 10)
test atom_frequent::large_docs                 ... bench:      13,576 ns/iter (+/- 664)
test atom_frequent::large_docs_first_ten       ... bench:         204 ns/iter (+/- 9)
test atom_frequent::typical                    ... bench:      13,507 ns/iter (+/- 509)
test atom_frequent::typical_first_ten          ... bench:         202 ns/iter (+/- 10)
test atom_seldom::large_collection             ... bench:       1,401 ns/iter (+/- 14)
test atom_seldom::large_collection_first_ten   ... bench:         244 ns/iter (+/- 1)
test atom_seldom::large_docs                   ... bench:       1,414 ns/iter (+/- 68)
test atom_seldom::large_docs_first_ten         ... bench:         236 ns/iter (+/- 6)
test atom_seldom::typical                      ... bench:         130 ns/iter (+/- 0)
test atom_seldom::typical_first_ten            ... bench:         128 ns/iter (+/- 0)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured
**** LIST_CHUNKSIZE: 1024
running 12 tests
test atom_frequent::large_collection           ... bench:     135,210 ns/iter (+/- 520)
test atom_frequent::large_collection_first_ten ... bench:         205 ns/iter (+/- 3)
test atom_frequent::large_docs                 ... bench:      13,537 ns/iter (+/- 109)
test atom_frequent::large_docs_first_ten       ... bench:         204 ns/iter (+/- 9)
test atom_frequent::typical                    ... bench:      13,523 ns/iter (+/- 98)
test atom_frequent::typical_first_ten          ... bench:         202 ns/iter (+/- 2)
test atom_seldom::large_collection             ... bench:       1,429 ns/iter (+/- 13)
test atom_seldom::large_collection_first_ten   ... bench:         234 ns/iter (+/- 11)
test atom_seldom::large_docs                   ... bench:       1,316 ns/iter (+/- 7)
test atom_seldom::large_docs_first_ten         ... bench:         240 ns/iter (+/- 10)
test atom_seldom::typical                      ... bench:         198 ns/iter (+/- 10)
test atom_seldom::typical_first_ten            ... bench:         196 ns/iter (+/- 9)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured

** Vec
*** ce7fc68
running 12 tests
test atom_frequent::large_collection           ... bench:      43,132 ns/iter (+/- 1,018)
test atom_frequent::large_collection_first_ten ... bench:         113 ns/iter (+/- 2)
test atom_frequent::large_docs                 ... bench:       4,400 ns/iter (+/- 242)
test atom_frequent::large_docs_first_ten       ... bench:         117 ns/iter (+/- 6)
test atom_frequent::typical                    ... bench:       4,430 ns/iter (+/- 293)
test atom_frequent::typical_first_ten          ... bench:         111 ns/iter (+/- 6)
test atom_seldom::large_collection             ... bench:         531 ns/iter (+/- 1)
test atom_seldom::large_collection_first_ten   ... bench:         134 ns/iter (+/- 0)
test atom_seldom::large_docs                   ... bench:         459 ns/iter (+/- 4)
test atom_seldom::large_docs_first_ten         ... bench:         130 ns/iter (+/- 6)
test atom_seldom::typical                      ... bench:         132 ns/iter (+/- 0)
test atom_seldom::typical_first_ten            ... bench:         125 ns/iter (+/- 0)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured

** CompressedRamStorage
*** 0e8441e
running 12 tests
test atom_frequent::large_collection           ... bench:   2,836,361 ns/iter (+/- 128,371)
test atom_frequent::large_collection_first_ten ... bench:   2,696,215 ns/iter (+/- 16,535)
test atom_frequent::large_docs                 ... bench:   1,779,831 ns/iter (+/- 4,906)
test atom_frequent::large_docs_first_ten       ... bench:   1,775,284 ns/iter (+/- 2,831)
test atom_frequent::typical                    ... bench:     270,341 ns/iter (+/- 3,172)
test atom_frequent::typical_first_ten          ... bench:     265,721 ns/iter (+/- 12,556)
test atom_seldom::large_collection             ... bench:      11,731 ns/iter (+/- 56)
test atom_seldom::large_collection_first_ten   ... bench:      11,297 ns/iter (+/- 37)
test atom_seldom::large_docs                   ... bench:       9,976 ns/iter (+/- 623)
test atom_seldom::large_docs_first_ten         ... bench:       9,513 ns/iter (+/- 68)
test atom_seldom::typical                      ... bench:       1,326 ns/iter (+/- 8)
test atom_seldom::typical_first_ten            ... bench:       1,379 ns/iter (+/- 62)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured
** ChunkedStorage
*** d69ddac
running 12 tests
test atom_frequent::large_collection           ... bench:  16,829,410 ns/iter (+/- 2,209,153)
test atom_frequent::large_collection_first_ten ... bench:  16,853,381 ns/iter (+/- 1,515,223)
test atom_frequent::typical                    ... bench:     381,276 ns/iter (+/- 24,567)
test atom_frequent::typical_first_ten          ... bench:     395,656 ns/iter (+/- 29,714)
test atom_seldom::large_collection             ... bench:      10,687 ns/iter (+/- 700)
test atom_seldom::large_collection_first_ten   ... bench:       9,901 ns/iter (+/- 382)
test atom_seldom::typical                      ... bench:       1,137 ns/iter (+/- 13)
test atom_seldom::typical_first_ten            ... bench:       1,165 ns/iter (+/- 70)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured
//Note to self. Removed large_docs because currently not working
*** c6f492e
running 12 tests
test atom_frequent::large_collection           ... bench:   2,902,003 ns/iter (+/- 82,919)
test atom_frequent::large_collection_first_ten ... bench:   2,851,847 ns/iter (+/- 17,516)
test atom_frequent::typical                    ... bench:     290,777 ns/iter (+/- 15,491)
test atom_frequent::typical_first_ten          ... bench:     285,587 ns/iter (+/- 13,727)
test atom_seldom::large_collection             ... bench:      11,292 ns/iter (+/- 664)
test atom_seldom::large_collection_first_ten   ... bench:      10,761 ns/iter (+/- 98)
test atom_seldom::typical                      ... bench:       1,763 ns/iter (+/- 104)
test atom_seldom::typical_first_ten            ... bench:       1,725 ns/iter (+/- 13)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured
//Note to self. Removed large_docs because currently not working

*** 3bb2c31
running 12 tests
test atom_frequent::large_collection           ... bench:   6,533,096 ns/iter (+/- 431,718)
test atom_frequent::large_collection_first_ten ... bench:   6,397,006 ns/iter (+/- 115,997)
test atom_frequent::typical                    ... bench:     668,582 ns/iter (+/- 2,887)
test atom_frequent::typical_first_ten          ... bench:     664,420 ns/iter (+/- 2,410)
test atom_seldom::large_collection             ... bench:      17,992 ns/iter (+/- 973)
test atom_seldom::large_collection_first_ten   ... bench:      17,531 ns/iter (+/- 850)
test atom_seldom::typical                      ... bench:         999 ns/iter (+/- 43)
test atom_seldom::typical_first_ten            ... bench:       1,015 ns/iter (+/- 49)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured
*** 416578e
running 12 tests
test atom_frequent::large_collection           ... bench:   6,475,047 ns/iter (+/- 305,035)
test atom_frequent::large_collection_first_ten ... bench:   6,389,854 ns/iter (+/- 199,886)
test atom_frequent::typical                    ... bench:     665,949 ns/iter (+/- 2,694)
test atom_frequent::typical_first_ten          ... bench:     661,702 ns/iter (+/- 2,420)
test atom_seldom::large_collection             ... bench:      24,583 ns/iter (+/- 57)
test atom_seldom::large_collection_first_ten   ... bench:      25,192 ns/iter (+/- 1,512)
test atom_seldom::typical                      ... bench:       1,729 ns/iter (+/- 36)
test atom_seldom::typical_first_ten            ... bench:       1,713 ns/iter (+/- 97)

test result: ok. 0 passed; 0 failed; 0 ignored; 12 measured
* New Boolean_Query
** bbd0754
running 42 tests
test and_frequent_frequent::large_collection           ... bench:  12,331,892 ns/iter (+/- 1,817,286)
test and_frequent_frequent::large_collection_first_ten ... bench:  12,173,677 ns/iter (+/- 477,568)
test and_frequent_frequent::large_documents_collection ... bench:   8,996,748 ns/iter (+/- 338,867)
test and_frequent_frequent::large_documents_first_ten  ... bench:   8,796,308 ns/iter (+/- 314,049)
test and_frequent_frequent::typical                    ... bench:   1,274,830 ns/iter (+/- 48,450)
test and_frequent_frequent::typical_first_ten          ... bench:   1,252,974 ns/iter (+/- 49,964)
test and_frequent_seldom::large_collection             ... bench:   7,258,424 ns/iter (+/- 1,265,403)
test and_frequent_seldom::large_collection_first_ten   ... bench:   7,187,911 ns/iter (+/- 1,178,599)
test and_frequent_seldom::large_documents_collection   ... bench:   4,806,007 ns/iter (+/- 145,416)
test and_frequent_seldom::large_documents_first_ten    ... bench:   4,820,310 ns/iter (+/- 195,086)
test and_frequent_seldom::typical                      ... bench:     677,991 ns/iter (+/- 22,846)
test and_frequent_seldom::typical_first_ten            ... bench:     663,491 ns/iter (+/- 17,449)
test and_seldom_seldom::large_collection               ... bench:      35,985 ns/iter (+/- 1,893)
test and_seldom_seldom::large_collection_first_ten     ... bench:      35,599 ns/iter (+/- 1,195)
test and_seldom_seldom::large_documents_collection     ... bench:      47,694 ns/iter (+/- 1,938)
test and_seldom_seldom::large_documents_first_ten      ... bench:      47,372 ns/iter (+/- 866)
test and_seldom_seldom::typical                        ... bench:       3,521 ns/iter (+/- 233)
test and_seldom_seldom::typical_first_ten              ... bench:       3,503 ns/iter (+/- 55)
test atom_frequent::large_collection                   ... bench:   6,372,295 ns/iter (+/- 312,688)
test atom_frequent::large_collection_first_ten         ... bench:   6,391,588 ns/iter (+/- 326,134)
test atom_frequent::large_documents_collection         ... bench:   4,806,137 ns/iter (+/- 111,404)
test atom_frequent::large_documents_first_ten          ... bench:   4,809,719 ns/iter (+/- 239,437)
test atom_frequent::typical                            ... bench:     666,699 ns/iter (+/- 33,249)
test atom_frequent::typical_first_ten                  ... bench:     661,243 ns/iter (+/- 28,657)
test atom_seldom::large_collection                     ... bench:      17,412 ns/iter (+/- 1,027)
test atom_seldom::large_collection_first_ten           ... bench:      17,054 ns/iter (+/- 686)
test atom_seldom::large_documents_collection           ... bench:      21,507 ns/iter (+/- 588)
test atom_seldom::large_documents_first_ten            ... bench:      21,208 ns/iter (+/- 583)
test atom_seldom::typical                              ... bench:       1,929 ns/iter (+/- 76)
test atom_seldom::typical_first_ten                    ... bench:       1,947 ns/iter (+/- 60)
test in_order_frequent::large_collection               ... bench:  19,360,593 ns/iter (+/- 885,414)
test in_order_frequent::large_collection_first_ten     ... bench:  19,187,484 ns/iter (+/- 1,209,049)
test in_order_frequent::large_documents_collection     ... bench:  13,949,463 ns/iter (+/- 696,489)
test in_order_frequent::large_documents_first_ten      ... bench:  13,423,019 ns/iter (+/- 682,585)
test in_order_frequent::typical                        ... bench:   2,011,313 ns/iter (+/- 125,012)
test in_order_frequent::typical_first_ten              ... bench:   1,983,147 ns/iter (+/- 61,249)
test in_order_seldom::large_collection                 ... bench:      67,338 ns/iter (+/- 1,206)
test in_order_seldom::large_collection_first_ten       ... bench:      67,267 ns/iter (+/- 979)
test in_order_seldom::large_documents_collection       ... bench:      85,661 ns/iter (+/- 1,201)
test in_order_seldom::large_documents_first_ten        ... bench:      75,535 ns/iter (+/- 2,708)
test in_order_seldom::typical                          ... bench:       5,570 ns/iter (+/- 346)
test in_order_seldom::typical_first_ten                ... bench:       5,410 ns/iter (+/- 265)

test result: ok. 0 passed; 0 failed; 0 ignored; 42 measured

** efbaf37
running 42 tests
test and_frequent_frequent::large_collection           ... bench:  68,280,509 ns/iter (+/- 959,499)
test and_frequent_frequent::large_collection_first_ten ... bench:      41,535 ns/iter (+/- 417)
test and_frequent_frequent::large_documents_collection ... bench:  12,017,544 ns/iter (+/- 11,426)
test and_frequent_frequent::large_documents_first_ten  ... bench:     119,682 ns/iter (+/- 290)
test and_frequent_frequent::typical                    ... bench:   7,086,169 ns/iter (+/- 121,023)
test and_frequent_frequent::typical_first_ten          ... bench:      40,457 ns/iter (+/- 1,868)
test and_frequent_seldom::large_collection             ... bench:     620,392 ns/iter (+/- 39,776)
test and_frequent_seldom::large_collection_first_ten   ... bench:      64,947 ns/iter (+/- 3,421)
test and_frequent_seldom::large_documents_collection   ... bench:     874,826 ns/iter (+/- 45,903)
test and_frequent_seldom::large_documents_first_ten    ... bench:      98,641 ns/iter (+/- 5,813)
test and_frequent_seldom::typical                      ... bench:     109,744 ns/iter (+/- 7,101)
test and_frequent_seldom::typical_first_ten            ... bench:      77,020 ns/iter (+/- 3,818)
test and_seldom_seldom::large_collection               ... bench:     908,118 ns/iter (+/- 32,970)
test and_seldom_seldom::large_collection_first_ten     ... bench:     897,672 ns/iter (+/- 45,134)
test and_seldom_seldom::large_documents_collection     ... bench:     773,177 ns/iter (+/- 36,202)
test and_seldom_seldom::large_documents_first_ten      ... bench:     787,246 ns/iter (+/- 41,182)
test and_seldom_seldom::typical                        ... bench:      17,161 ns/iter (+/- 793)
test and_seldom_seldom::typical_first_ten              ... bench:      16,912 ns/iter (+/- 880)
test atom_frequent::large_collection                   ... bench:   6,067,820 ns/iter (+/- 340,712)
test atom_frequent::large_collection_first_ten         ... bench:       6,213 ns/iter (+/- 254)
test atom_frequent::large_documents_collection         ... bench:   4,679,663 ns/iter (+/- 217,801)
test atom_frequent::large_documents_first_ten          ... bench:      49,879 ns/iter (+/- 2,572)
test atom_frequent::typical                            ... bench:     632,035 ns/iter (+/- 24,198)
test atom_frequent::typical_first_ten                  ... bench:       6,382 ns/iter (+/- 14)
test atom_seldom::large_collection                     ... bench:      15,320 ns/iter (+/- 66)
test atom_seldom::large_collection_first_ten           ... bench:       2,023 ns/iter (+/- 105)
test atom_seldom::large_documents_collection           ... bench:      13,874 ns/iter (+/- 457)
test atom_seldom::large_documents_first_ten            ... bench:       1,950 ns/iter (+/- 74)
test atom_seldom::typical                              ... bench:       1,906 ns/iter (+/- 97)
test atom_seldom::typical_first_ten                    ... bench:       1,130 ns/iter (+/- 60)
test in_order_frequent::large_collection               ... bench:  73,648,675 ns/iter (+/- 2,907,607)
test in_order_frequent::large_collection_first_ten     ... bench:  65,534,777 ns/iter (+/- 2,181,449)
test in_order_frequent::large_documents_collection     ... bench:  17,588,323 ns/iter (+/- 833,329)
test in_order_frequent::large_documents_first_ten      ... bench:  16,196,271 ns/iter (+/- 734,515)
test in_order_frequent::typical                        ... bench:   7,553,448 ns/iter (+/- 470,796)
test in_order_frequent::typical_first_ten              ... bench:   7,567,725 ns/iter (+/- 452,532)
test in_order_seldom::large_collection                 ... bench:     903,870 ns/iter (+/- 20,888)
test in_order_seldom::large_collection_first_ten       ... bench:     946,989 ns/iter (+/- 61,595)
test in_order_seldom::large_documents_collection       ... bench:     831,883 ns/iter (+/- 45,327)
test in_order_seldom::large_documents_first_ten        ... bench:     788,305 ns/iter (+/- 18,036)
test in_order_seldom::typical                          ... bench:      11,462 ns/iter (+/- 245)
test in_order_seldom::typical_first_ten                ... bench:      11,517 ns/iter (+/- 202)

test result: ok. 0 passed; 0 failed; 0 ignored; 42 measured
